/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.fls.ppe.guis;

import dev.fls.ppe.accounts.Client;
import dev.fls.ppe.managers.AccountManager;
import dev.fls.ppe.managers.ClientManager;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author b.siniak
 */
public class ClientsGUI extends javax.swing.JFrame {

    private Client currentClient;
    int id;

    /**
     * Creates new form GlobalGUI
     */
    public ClientsGUI() {
        initComponents();
        this.setTitle("Perpi&Co - Clients");
        modifierPanel.setVisible(false);
	updateClientsList();
        /*
        untoggleAdminOptions();*/
    }

    private void untoggleAdminOptions() {
        if(AccountManager.getInstance().getAccountsConnected().get(0).getIdProfil() != 1) {
            adminButton.setVisible(false);
        }
    }

    private void updateClientsList() {
        ClientManager.getInstance().addAllClientsFromDB();
        DefaultListModel listeClientsModel = (DefaultListModel) listeClients.getModel();
        listeClientsModel.clear();
        for(int i = 0; i < ClientManager.getInstance().getClients().size(); i++) {
            Client client = ClientManager.getInstance().getClients().get(i);
            listeClientsModel.add(i, client.getNom() + " " + client.getPrenom());
        }
        listeClients.setModel(listeClientsModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventesPanel1 = new javax.swing.JPanel();
        nomLabel1 = new javax.swing.JLabel();
        prenomLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        telephoneLabel1 = new javax.swing.JLabel();
        prenomField1 = new javax.swing.JTextField();
        nomField1 = new javax.swing.JTextField();
        emailField1 = new javax.swing.JTextField();
        telephoneField1 = new javax.swing.JTextField();
        creerFactureButton1 = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        produitsButton = new javax.swing.JButton();
        clientsButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        telephoneField = new javax.swing.JTextField();
        telephoneLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        prenomField = new javax.swing.JTextField();
        prenomLabel = new javax.swing.JLabel();
        nomField = new javax.swing.JTextField();
        nomLabel = new javax.swing.JLabel();
        addClientButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeClients = new JList<Object>();
        precedentButton = new javax.swing.JButton();
        suivantButton = new javax.swing.JButton();
        selectionButton = new javax.swing.JButton();
        modifierPanel = new javax.swing.JPanel();
        addClientButton1 = new javax.swing.JButton();
        telephoneField2 = new javax.swing.JTextField();
        telephoneLabel2 = new javax.swing.JLabel();
        emailField2 = new javax.swing.JTextField();
        emailLabel2 = new javax.swing.JLabel();
        prenomField2 = new javax.swing.JTextField();
        prenomLabel2 = new javax.swing.JLabel();
        nomField2 = new javax.swing.JTextField();
        nomLabel2 = new javax.swing.JLabel();

        ventesPanel1.setBackground(new java.awt.Color(96, 96, 96));
        ventesPanel1.setEnabled(false);

        nomLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        nomLabel1.setForeground(new java.awt.Color(255, 255, 255));
        nomLabel1.setText("Nom");

        prenomLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        prenomLabel1.setForeground(new java.awt.Color(255, 255, 255));
        prenomLabel1.setText("Prénom");

        emailLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel1.setText("Email");

        telephoneLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        telephoneLabel1.setForeground(new java.awt.Color(255, 255, 255));
        telephoneLabel1.setText("Téléphone");

        prenomField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        nomField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        emailField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        telephoneField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        creerFactureButton1.setBackground(new java.awt.Color(16, 86, 160));
        creerFactureButton1.setForeground(new java.awt.Color(255, 255, 255));
        creerFactureButton1.setText("Créer la facture");

        javax.swing.GroupLayout ventesPanel1Layout = new javax.swing.GroupLayout(ventesPanel1);
        ventesPanel1.setLayout(ventesPanel1Layout);
        ventesPanel1Layout.setHorizontalGroup(
            ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventesPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomLabel1)
                    .addComponent(prenomLabel1)
                    .addGroup(ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(prenomField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(nomField1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(emailLabel1)
                    .addGroup(ventesPanel1Layout.createSequentialGroup()
                        .addGroup(ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telephoneLabel1)
                            .addComponent(telephoneField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(creerFactureButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventesPanel1Layout.setVerticalGroup(
            ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventesPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(creerFactureButton1)
                    .addGroup(ventesPanel1Layout.createSequentialGroup()
                        .addComponent(nomLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prenomLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prenomField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telephoneLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telephoneField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(96, 96, 96));

        menuPanel.setBackground(new java.awt.Color(96, 96, 96));

        produitsButton.setBackground(new java.awt.Color(16, 86, 160));
        produitsButton.setForeground(new java.awt.Color(255, 255, 255));
        produitsButton.setText("PRODUITS");
        produitsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produitsButtonActionPerformed(evt);
            }
        });

        clientsButton.setBackground(new java.awt.Color(16, 86, 160));
        clientsButton.setForeground(new java.awt.Color(255, 255, 255));
        clientsButton.setText("CLIENTS");

        adminButton.setBackground(new java.awt.Color(16, 86, 160));
        adminButton.setForeground(new java.awt.Color(255, 255, 255));
        adminButton.setText("ADMIN");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        tabs.setBackground(new java.awt.Color(96, 96, 96));

        jPanel1.setBackground(new java.awt.Color(96, 96, 96));

        telephoneField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        telephoneLabel.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        telephoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        telephoneLabel.setText("Téléphone");

        emailField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        emailLabel.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email");

        prenomField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        prenomLabel.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        prenomLabel.setForeground(new java.awt.Color(255, 255, 255));
        prenomLabel.setText("Prénom");

        nomField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        nomLabel.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        nomLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomLabel.setText("Nom");

        addClientButton.setBackground(new java.awt.Color(16, 86, 160));
        addClientButton.setForeground(new java.awt.Color(255, 255, 255));
        addClientButton.setText("Ajouter le client");
        addClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(addClientButton))
                    .addComponent(nomLabel)
                    .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenomLabel)
                    .addComponent(prenomField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneLabel)
                    .addComponent(telephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomLabel)
                .addGap(3, 3, 3)
                .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(prenomLabel)
                .addGap(3, 3, 3)
                .addComponent(prenomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(emailLabel)
                .addGap(3, 3, 3)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(telephoneLabel)
                .addGap(3, 3, 3)
                .addComponent(telephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addClientButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Créer", jPanel1);
        jPanel3.setBackground(new java.awt.Color(96, 96, 96));

        /*listeClients.setModel(new javax.swing.DefaultListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }

        });*/
        listeClients.setModel(new DefaultListModel<>());
        jScrollPane1.setViewportView(listeClients);

        precedentButton.setBackground(new java.awt.Color(16, 86, 160));
        precedentButton.setForeground(new java.awt.Color(255, 255, 255));
        precedentButton.setText("Précédent");
        precedentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precedentButtonActionPerformed(evt);
            }
        });

        suivantButton.setBackground(new java.awt.Color(16, 86, 160));
        suivantButton.setForeground(new java.awt.Color(255, 255, 255));
        suivantButton.setText("Suivant");
        suivantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suivantButtonActionPerformed(evt);
            }
        });

        selectionButton.setBackground(new java.awt.Color(16, 86, 160));
        selectionButton.setForeground(new java.awt.Color(255, 255, 255));
        selectionButton.setText("Séléction");
        selectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(precedentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suivantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precedentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suivantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Afficher", jPanel3);

        modifierPanel.setBackground(new java.awt.Color(96, 96, 96));

        addClientButton1.setBackground(new java.awt.Color(16, 86, 160));
        addClientButton1.setForeground(new java.awt.Color(255, 255, 255));
        addClientButton1.setText("Modifier le client");
        addClientButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientButton1ActionPerformed(evt);
            }
        });

        telephoneField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        telephoneLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        telephoneLabel2.setForeground(new java.awt.Color(255, 255, 255));
        telephoneLabel2.setText("Téléphone");

        emailField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        emailLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        emailLabel2.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel2.setText("Email");

        prenomField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        prenomLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        prenomLabel2.setForeground(new java.awt.Color(255, 255, 255));
        prenomLabel2.setText("Prénom");

        nomField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        nomLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        nomLabel2.setForeground(new java.awt.Color(255, 255, 255));
        nomLabel2.setText("Nom");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(modifierPanel);
        modifierPanel.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(addClientButton1))
                    .addComponent(nomLabel2)
                    .addComponent(nomField2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenomLabel2)
                    .addComponent(prenomField2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel2)
                    .addComponent(emailField2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneLabel2)
                    .addComponent(telephoneField2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomLabel2)
                .addGap(3, 3, 3)
                .addComponent(nomField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(prenomLabel2)
                .addGap(3, 3, 3)
                .addComponent(prenomField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(emailLabel2)
                .addGap(3, 3, 3)
                .addComponent(emailField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(telephoneLabel2)
                .addGap(3, 3, 3)
                .addComponent(telephoneField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addClientButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Modifier", modifierPanel);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(produitsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(produitsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(clientsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ACTIONS


    private void precedentButtonActionPerformed(ActionEvent evt) {
        if(listeClients.getSelectedIndex() > 0) {
            listeClients.setSelectedIndex(listeClients.getSelectedIndex() - 1);
        }
    }

    private void suivantButtonActionPerformed(ActionEvent evt) {
        if(listeClients.getSelectedIndex() + 1 < listeClients.getModel().getSize()) {
            listeClients.setSelectedIndex(listeClients.getSelectedIndex() + 1);
        }
    }

    private void selectionButtonActionPerformed(java.awt.event.ActionEvent evt) {
        id = listeClients.getSelectedIndex() + 1;
        currentClient = ClientManager.getInstance().getClientById(id);
        tabs.setSelectedComponent(modifierPanel);
        nomField2.setText(currentClient.getNom());
        prenomField2.setText(currentClient.getPrenom());
        emailField2.setText(currentClient.getEmail());
        telephoneField2.setText(currentClient.getTelephone());
    }

    private void addClientButtonActionPerformed(java.awt.event.ActionEvent evt) {
        ClientManager.getInstance().addClient(new Client(1, nomField.getText(), prenomField.getText(), emailField.getText(), telephoneField.getText()));
    }

    public void addClientButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        currentClient = ClientManager.getInstance().getClientById(id);
        currentClient.setNom(nomField2.getText());
        currentClient.setPrenom(prenomField2.getText());
        currentClient.setEmail(emailField2.getText());
        currentClient.setTelephone(telephoneField2.getText());
        System.out.println("ID CLIENT " + currentClient.getId() + " - ID LISTE " + id);
        ClientManager.getInstance().updateClientInfos(currentClient);

    }

    private void produitsButtonActionPerformed(java.awt.event.ActionEvent evt) {
        ProduitsGUI produitsGUI = new ProduitsGUI();
        produitsGUI.setLocation(this.getLocation());
        produitsGUI.setVisible(true);
        this.setVisible(false);
        dispose();
    }

    private void adminButtonActionPerformed(ActionEvent evt) {
        AdminGUI adminGUI = new AdminGUI();
        adminGUI.setLocation(this.getLocation());
        adminGUI.setVisible(true);
        this.setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientButton;
    private javax.swing.JButton addClientButton1;
    private javax.swing.JButton adminButton;
    private javax.swing.JButton clientsButton;
    private javax.swing.JButton creerFactureButton1;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField emailField1;
    private javax.swing.JTextField emailField2;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private JList<Object> listeClients;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel modifierPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField nomField;
    private javax.swing.JTextField nomField1;
    private javax.swing.JTextField nomField2;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JLabel nomLabel1;
    private javax.swing.JLabel nomLabel2;
    private javax.swing.JTextField prenomField;
    private javax.swing.JTextField prenomField1;
    private javax.swing.JTextField prenomField2;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JLabel prenomLabel1;
    private javax.swing.JLabel prenomLabel2;
    private javax.swing.JButton produitsButton;
    private javax.swing.JButton precedentButton;
    private javax.swing.JButton suivantButton;
    private javax.swing.JButton selectionButton;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTextField telephoneField;
    private javax.swing.JTextField telephoneField1;
    private javax.swing.JTextField telephoneField2;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JLabel telephoneLabel1;
    private javax.swing.JLabel telephoneLabel2;
    private javax.swing.JPanel ventesPanel1;
    // End of variables declaration//GEN-END:variables
}
