/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.fls.ppe.guis;

import dev.fls.ppe.accounts.Categorie;
import dev.fls.ppe.accounts.Product;
import dev.fls.ppe.managers.AccountManager;
import dev.fls.ppe.managers.DataAccessObject;
import dev.fls.ppe.managers.ProductManager;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author b.siniak
 */
public class ProduitsGUI extends javax.swing.JFrame {

    /**
     * Creates new form GlobalGUI
     */
    public ProduitsGUI() {
        initComponents();
        this.setTitle("Perpi&Co - Produits");
        updateCategoriesList();
        untoggleAdminOptions();
    }

    private void untoggleAdminOptions() {
        if(AccountManager.getInstance().getAccountsConnected().get(0).getIdProfil() != 1) {
            adminButton.setVisible(false);
            gererProduit.setVisible(false);
            jTabbedPane1.remove(gererProduit);
        }
    }

    private void updateCategoriesList() {
        categoriesList.removeAllItems();
        ProductManager.getInstance().getCategoriesFromDB();
        DefaultComboBoxModel model = (DefaultComboBoxModel) categoriesList.getModel();
        for(int i = 0; i < ProductManager.getInstance().getCategories().size(); i++) {
            Categorie categorie = ProductManager.getInstance().getCategories().get(i);
            model.addElement(categorie.getNom());
        }
        categoriesList.setModel(model);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventesPanel1 = new javax.swing.JPanel();
        prenomLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        telephoneLabel1 = new javax.swing.JLabel();
        prenomField1 = new javax.swing.JTextField();
        nomField1 = new javax.swing.JTextField();
        emailField1 = new javax.swing.JTextField();
        telephoneField1 = new javax.swing.JTextField();
        creerVenteButton = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCategorie = new javax.swing.JPanel();
        categoriesList = new JComboBox<Object>();
        CategoriesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsList = new JList<Object>();
        ventesPanel = new javax.swing.JPanel();
        creerFactureButton = new javax.swing.JButton();
        gererProduit = new javax.swing.JPanel();
        nomLabel2 = new javax.swing.JLabel();
        descriptionProduitLabel = new javax.swing.JLabel();
        emailLabel2 = new javax.swing.JLabel();
        prenomField2 = new javax.swing.JTextField();
        nomField2 = new javax.swing.JTextField();
        emailField2 = new javax.swing.JTextField();
        addProductButton = new javax.swing.JButton();
        produitsButton = new javax.swing.JButton();
        clientsButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();

        ventesPanel1.setBackground(new java.awt.Color(96, 96, 96));
        ventesPanel1.setEnabled(false);


        prenomLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        prenomLabel1.setForeground(new java.awt.Color(255, 255, 255));
        prenomLabel1.setText("Pr�nom");

        emailLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel1.setText("Email");

        telephoneLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        telephoneLabel1.setForeground(new java.awt.Color(255, 255, 255));
        telephoneLabel1.setText("Téléphone");

        prenomField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        nomField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        emailField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        telephoneField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        creerVenteButton.setBackground(new java.awt.Color(16, 86, 160));
        creerVenteButton.setForeground(new java.awt.Color(255, 255, 255));
        creerVenteButton.setText("Créer une vente");
        creerVenteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                creerVenteButtonActionPerformed(e);
            }
        });

        javax.swing.GroupLayout ventesPanel1Layout = new javax.swing.GroupLayout(ventesPanel1);
        ventesPanel1.setLayout(ventesPanel1Layout);
        ventesPanel1Layout.setHorizontalGroup(
            ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventesPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenomLabel1)
                    .addGroup(ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(prenomField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(nomField1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(emailLabel1)
                    .addGroup(ventesPanel1Layout.createSequentialGroup()
                        .addGroup(ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telephoneLabel1)
                            .addComponent(telephoneField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(creerVenteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventesPanel1Layout.setVerticalGroup(
            ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventesPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(creerVenteButton)
                    .addGroup(ventesPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prenomLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prenomField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telephoneLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telephoneField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(96, 96, 96));

        menuPanel.setBackground(new java.awt.Color(96, 96, 96));

        panelCategorie.setBackground(new java.awt.Color(96, 96, 96));
        panelCategorie.setEnabled(false);

        categoriesList.setModel(new javax.swing.DefaultComboBoxModel<>());
        categoriesList.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                categoriesListActionPerformed(evt);
            }
        });

        CategoriesLabel.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        CategoriesLabel.setForeground(new java.awt.Color(255, 255, 255));
        CategoriesLabel.setText("Catégories");

        productsList.setModel(new DefaultListModel<>());
        jScrollPane1.setViewportView(productsList);

        javax.swing.GroupLayout panelCategorieLayout = new javax.swing.GroupLayout(panelCategorie);
        panelCategorie.setLayout(panelCategorieLayout);
        panelCategorieLayout.setHorizontalGroup(
            panelCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategorieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(categoriesList, 0, 149, Short.MAX_VALUE)
                    .addComponent(CategoriesLabel)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCategorieLayout.setVerticalGroup(
            panelCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategorieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CategoriesLabel)
                .addGap(1, 1, 1)
                .addComponent(categoriesList, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Catégories", panelCategorie);

        ventesPanel.setBackground(new java.awt.Color(96, 96, 96));
        ventesPanel.setEnabled(false);
        //ventesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        //ventesPanel.add(telephoneLabel, new AbsoluteConstraints(10, 130, -1, -1));

        //ventesPanel.add(prenomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 128, -1));

        creerFactureButton.setBackground(new java.awt.Color(16, 86, 160));
        creerFactureButton.setForeground(new java.awt.Color(255, 255, 255));
        creerFactureButton.setText("Créer une vente");
        creerFactureButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                creerVenteButtonActionPerformed(e);
            }
        });
        //ventesPanel.add(creerFactureButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        ventesPanel.add(creerFactureButton);

        jTabbedPane1.addTab("Ventes", ventesPanel);

        gererProduit.setBackground(new java.awt.Color(96, 96, 96));
        gererProduit.setEnabled(false);

        nomLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        nomLabel2.setForeground(new java.awt.Color(255, 255, 255));
        nomLabel2.setText("Nom du produit");

        descriptionProduitLabel.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        descriptionProduitLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionProduitLabel.setText("Description");

        emailLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        emailLabel2.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel2.setText("Catégories");

        prenomField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        nomField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        emailField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        addProductButton.setBackground(new java.awt.Color(16, 86, 160));
        addProductButton.setForeground(new java.awt.Color(255, 255, 255));
        addProductButton.setText("Ajouter un produit");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventesPanel2Layout = new javax.swing.GroupLayout(gererProduit);
        gererProduit.setLayout(ventesPanel2Layout);
        ventesPanel2Layout.setHorizontalGroup(
            ventesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventesPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addProductButton)
                    .addGroup(ventesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emailField2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomLabel2)
                        .addComponent(descriptionProduitLabel)
                        .addGroup(ventesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(prenomField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(nomField2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(emailLabel2)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        ventesPanel2Layout.setVerticalGroup(
            ventesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventesPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionProduitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prenomField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addProductButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gérer", gererProduit);

        produitsButton.setBackground(new java.awt.Color(16, 86, 160));
        produitsButton.setForeground(new java.awt.Color(255, 255, 255));
        produitsButton.setText("PRODUITS");
        produitsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produitsButtonActionPerformed(evt);
            }
        });

        clientsButton.setBackground(new java.awt.Color(16, 86, 160));
        clientsButton.setForeground(new java.awt.Color(255, 255, 255));
        clientsButton.setText("CLIENTS");
        clientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsButtonActionPerformed(evt);
            }
        });

        adminButton.setBackground(new java.awt.Color(16, 86, 160));
        adminButton.setForeground(new java.awt.Color(255, 255, 255));
        adminButton.setText("ADMIN");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(produitsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(produitsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(clientsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creerVenteButtonActionPerformed(ActionEvent e) {
        VenteGUI venteGUI = new VenteGUI();
        venteGUI.setLocation(this.getLocation());
        venteGUI.setVisible(true);
        this.setVisible(false);
dispose();
    }

    private void addProductButtonActionPerformed(ActionEvent evt) {
        try {
            ResultSet rs = DataAccessObject.getInstance().requeteSelection("SELECT count(*) AS count FROM produits");
            rs.first();
            int count = rs.getInt("count") + 1;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        //ProductManager.getInstance().addProduct(new Product(new Product(count, categorie, ))));
    }

    private void categoriesListActionPerformed(ActionEvent evt) {
        DefaultListModel listeProductsModel = (DefaultListModel) productsList.getModel();
        listeProductsModel.clear();
        ProductManager.getInstance().getProductsFromDB();
        if(ProductManager.getInstance().getProducts().size() > 0) {
            Categorie categorieSelected = null;

            for(int i = 0; i < ProductManager.getInstance().getProducts().size(); i++) {
                Product product = ProductManager.getInstance().getProducts().get(i);
                for(Categorie categorie : ProductManager.getInstance().getCategories()) {
                    if(categorie.getNom() == categoriesList.getSelectedItem()) {
                        categorieSelected = categorie;
                    }
                }
                if(product.getIdCategorie() == categorieSelected.getIdCategorie()) {
                    listeProductsModel.addElement(product.getNomProduit() + " - " + product.getPrix() + "€");
                }
            }
        } else {
            listeProductsModel.addElement("PAS DE PRODUITS POUR CETTE CATEGORIE");
        }
        productsList.setModel(listeProductsModel);
    }

    private void produitsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produitsButtonActionPerformed
    }//GEN-LAST:event_produitsButtonActionPerformed

    private void clientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsButtonActionPerformed
        ClientsGUI clientsGUI = new ClientsGUI();
        clientsGUI.setLocation(this.getLocation());
        clientsGUI.setVisible(true);
        this.setVisible(false);
dispose();
    }//GEN-LAST:event_clientsButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        AdminGUI adminGUI = new AdminGUI();
        adminGUI.setLocation(this.getLocation());
        adminGUI.setVisible(true);
        this.setVisible(false);
dispose();
    }//GEN-LAST:event_adminButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProduitsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProduitsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProduitsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProduitsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProduitsGUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoriesLabel;
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton adminButton;
    private JComboBox<Object> categoriesList;
    private javax.swing.JButton clientsButton;
    private javax.swing.JButton creerFactureButton;
    private javax.swing.JButton creerVenteButton;
    private javax.swing.JLabel descriptionProduitLabel;
    private javax.swing.JTextField emailField1;
    private javax.swing.JTextField emailField2;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField nomField1;
    private javax.swing.JTextField nomField2;
    private javax.swing.JLabel nomLabel2;
    private javax.swing.JPanel panelCategorie;
    private javax.swing.JTextField prenomField1;
    private javax.swing.JTextField prenomField2;
    private javax.swing.JLabel prenomLabel1;
    private JList<Object> productsList;
    private javax.swing.JList<String> productsList1;
    private javax.swing.JButton produitsButton;
    private javax.swing.JTextField telephoneField1;
    private javax.swing.JLabel telephoneLabel1;
    private javax.swing.JPanel ventesPanel;
    private javax.swing.JPanel ventesPanel1;
    private javax.swing.JPanel gererProduit;
    // End of variables declaration//GEN-END:variables
}
