/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.fls.ppe.guis;

import dev.fls.ppe.accounts.Product;
import dev.fls.ppe.managers.ProductManager;
import dev.fls.ppe.managers.VenteManager;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author b.siniak
 */
public class QuantiteGUI extends javax.swing.JFrame {

    private VenteGUI venteGUI;
    private Product product;

    public VenteGUI getVenteGUI() {
        return venteGUI;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
        quantiteField.setText(product.getQuantite() + "");
    }

    /**
     * Creates new form GlobalGUI
     * @param venteGUI
     */
    public QuantiteGUI(VenteGUI venteGUI) {
        initComponents();
        this.venteGUI = venteGUI;
        quantiteField.setText(1 + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventesPanel1 = new javax.swing.JPanel();
        nomLabel1 = new javax.swing.JLabel();
        prenomLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        telephoneLabel1 = new javax.swing.JLabel();
        prenomField1 = new javax.swing.JTextField();
        nomField1 = new javax.swing.JTextField();
        emailField1 = new javax.swing.JTextField();
        telephoneField1 = new javax.swing.JTextField();
        creerFactureButton1 = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        quantiteField = new javax.swing.JTextField();
        nomLabel2 = new javax.swing.JLabel();
        addProduct = new javax.swing.JButton();

        ventesPanel1.setBackground(new java.awt.Color(96, 96, 96));
        ventesPanel1.setEnabled(false);

        nomLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        nomLabel1.setForeground(new java.awt.Color(255, 255, 255));
        nomLabel1.setText("Nom");

        prenomLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        prenomLabel1.setForeground(new java.awt.Color(255, 255, 255));
        prenomLabel1.setText("Prénom");

        emailLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel1.setText("Email");

        telephoneLabel1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        telephoneLabel1.setForeground(new java.awt.Color(255, 255, 255));
        telephoneLabel1.setText("Téléphone");

        prenomField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        nomField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        emailField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        telephoneField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        creerFactureButton1.setBackground(new java.awt.Color(16, 86, 160));
        creerFactureButton1.setForeground(new java.awt.Color(255, 255, 255));
        creerFactureButton1.setText("Créer la facture");

        javax.swing.GroupLayout ventesPanel1Layout = new javax.swing.GroupLayout(ventesPanel1);
        ventesPanel1.setLayout(ventesPanel1Layout);
        ventesPanel1Layout.setHorizontalGroup(
            ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventesPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomLabel1)
                    .addComponent(prenomLabel1)
                    .addGroup(ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(prenomField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(nomField1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(emailLabel1)
                    .addGroup(ventesPanel1Layout.createSequentialGroup()
                        .addGroup(ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telephoneLabel1)
                            .addComponent(telephoneField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(creerFactureButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ventesPanel1Layout.setVerticalGroup(
            ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventesPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(creerFactureButton1)
                    .addGroup(ventesPanel1Layout.createSequentialGroup()
                        .addComponent(nomLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prenomLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prenomField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telephoneLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telephoneField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(96, 96, 96));

        menuPanel.setBackground(new java.awt.Color(96, 96, 96));

        quantiteField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        nomLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        nomLabel2.setForeground(new java.awt.Color(255, 255, 255));
        nomLabel2.setText("Quantité");

        addProduct.setBackground(new java.awt.Color(16, 86, 160));
        addProduct.setForeground(new java.awt.Color(255, 255, 255));
        addProduct.setText("Ajouter le produit");
        addProduct.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addProductActionPerformed(e);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomLabel2)
                    .addComponent(quantiteField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantiteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProductActionPerformed(ActionEvent e) {
        product.setQuantite(Integer.valueOf(quantiteField.getText()));
        VenteManager.getInstance().editProductQuantityInVente(venteGUI.vente, product);
        this.setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuantiteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuantiteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuantiteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuantiteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuantiteGUI(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JButton creerFactureButton1;
    private javax.swing.JTextField emailField1;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField nomField1;
    private javax.swing.JLabel nomLabel1;
    private javax.swing.JLabel nomLabel2;
    private javax.swing.JTextField prenomField1;
    private javax.swing.JLabel prenomLabel1;
    private javax.swing.JTextField quantiteField;
    private javax.swing.JTextField telephoneField1;
    private javax.swing.JLabel telephoneLabel1;
    private javax.swing.JPanel ventesPanel1;
    // End of variables declaration//GEN-END:variables
}
